# Generated by Django 4.1.7 on 2023-02-19 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/broker')),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_admin', models.IntegerField(blank=True, null=True)),
                ('comp_Name', models.CharField(max_length=200)),
                ('comp_Logo', models.ImageField(blank=True, null=True, upload_to='media/logo')),
                ('comp_Number', models.CharField(max_length=15)),
                ('comp_mail', models.EmailField(max_length=254)),
                ('comp_domain', models.TextField(blank=True)),
                ('comp_adress', models.TextField(blank=True)),
                ('comp_city', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(blank=True)),
                ('types', models.CharField(max_length=100)),
                ('living_area', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=100)),
                ('socail_number', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(blank=True)),
                ('types', models.CharField(max_length=100)),
                ('living_area', models.TextField(blank=True)),
                ('land_size', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('types', models.CharField(max_length=100)),
                ('city', models.TextField(blank=True)),
                ('adress', models.TextField(blank=True)),
                ('living_area', models.TextField(blank=True)),
                ('land_size', models.CharField(max_length=50)),
                ('rooms', models.TextField(blank=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('properties', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('id_broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.broker')),
            ],
        ),
        migrations.AddField(
            model_name='broker',
            name='id_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.company'),
        ),
    ]
