# Generated by Django 3.2 on 2023-02-21 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_broker_id_company_broker_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='id_broker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.broker'),
        ),
    ]
