# Generated by Django 3.2 on 2023-02-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_properties_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='broker'),
        ),
        migrations.AlterField(
            model_name='company',
            name='comp_Logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='properties',
            field=models.ImageField(blank=True, null=True, upload_to='properties'),
        ),
    ]
