# Generated by Django 3.2 on 2023-02-21 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20230221_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='id_broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.broker'),
        ),
    ]
