# Generated by Django 3.2 on 2023-02-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_properties_id_broker'),
    ]

    operations = [
        migrations.CreateModel(
            name='date_helper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='properties',
            name='date_time',
            field=models.ManyToManyField(blank=True, to='mainapp.date_helper'),
        ),
    ]
