# Generated by Django 3.2 on 2023-02-22 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20230222_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broker',
            old_name='owner',
            new_name='user',
        ),
    ]
